name: Run tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        exclude:  # Python < v3.8 does not support Apple Silicon ARM64.
          - python-version: "3.7"
            os: macos-latest
        include:  # So run those legacy versions on Intel CPUs.
          - python-version: "3.7"
            os: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        pip install pytest
        pip install -e .
        pip install -r requirements-test.txt
        pytest
